### ISSUE TITLE
Adjust io.py corresponding to ego.io naming changes

### ISSUE THREAD

**Issue by ulfmueller** [openego/ego.powerflow#22]
Once the ego.io has been changed the io.py has to be adjusted as well in a refactor-branch.

See ego.io issue: https://github.com/openego/ego.io/issues/8

**Comment by ulfmueller** [comment]
I added the refactor branch. Once the ego.io is adapted I would adjust the io.py within this branch ( https://github.com/openego/ego.powerflow/tree/refactor/adaptions-of-tablenames )

**Comment by mariusves** [comment]
This has been carried out.
