### ISSUE TITLE
conform db access using ego.io

### ISSUE THREAD

**Issue by nesnoj** [openego/ego.powerflow#23]
The original post was https://github.com/openego/data_processing/issues/13, further discussions can be found in https://github.com/openego/ego.io/issues/14#issuecomment-278313750:

> In either case we might aspire to bundle db access stuff in ego.io tools - currently db access is done using
> 1. oemof.db import statements (e.g. [here](https://github.com/openego/data_processing/blob/refactor/oedb-restructuring_v0.2/dataprocessing/python_scripts/peak_load_per_load_area.py#L19))
> 2. [data_proc io](https://github.com/openego/data_processing/blob/refactor/oedb-restructuring_v0.2/dataprocessing/tools/io.py) (e.g. [here](https://github.com/openego/data_processing/blob/refactor/oedb-restructuring_v0.2/dataprocessing/eGo_data_processing.py#L17))
> 3. [ego.powerflow tools](https://github.com/openego/ego.powerflow/blob/dev/egopowerflow/tools/tools.py) (e.g. [here](https://github.com/openego/ego.powerflow/blob/dev/egopowerflow/examples/hv_grid.py#L14))
> 
> We could move the `oedb_session()` function to ego.io and adjust all scripts in all repos to use it..?

This is on schedule for ego.io release v0.3 and has to be considered in ego.powerflow too.

**Comment by mariusves** [comment]
This will be further handled [here](https://github.com/openego/eTraGo/issues/61)!
