### ISSUE TITLE
Update of examples in refactor branch needed

### ISSUE THREAD

**Issue by mariusves** [openego/ego.powerflow#25]
Initial import of ego.io classes in examples still references the old schema, raises an error if used with the new version ego.io.

**Comment by eosram** [comment]
You can checkout the branch https://github.com/openego/ego.powerflow/tree/refactor/adaptions-of-tablenames in ego.powerflow and https://github.com/openego/ego.io/tree/refactor/updated_schema_structure in the ego.io repository. Although these changes are not merged back yet, both branches are created to solve this issue.

**Comment by mariusves** [comment]
Issue solved already
