### ISSUE TITLE
Adapt for versioned grid schema / single function for call for data

### ISSUE THREAD

**Issue by eosram** [openego/ego.powerflow#27]
Within ego.powerflow there is no way of specifying the grid schema, which is subject to versioning and thus will be a more reliable and transparent, because reproducable, data source for our applications than the model_draft. Specifying this schema and a version number should be possible. It might also be beneficial to refactor ego.powerflow, that a call for data/building a pypsa network requires calling a single function in dependent applications.

**Comment by eosram** [comment]
Filter for nan values while executing import_pq_set should be part of the refactoring process.

**Comment by ulfmueller** [comment]
see [ego.io update](https://github.com/openego/ego.io/blob/refactor/schema_structure_dp_v0.2/egoio/db_tables/grid.py). Now the functionality could be tested.

**Comment by eosram** [comment]
This is up and running for some time and could most likely be closed, although filtering for nan values while importing time varying data is not part of the method series_by_scenario https://github.com/openego/ego.powerflow/blob/dev/egopowerflow/tools/io.py#L164-L200. Is this still relevant though?

**Comment by mariusves** [comment]
@s3pp 
I'm currently moving open ego.pf issues over to eTrago. Do you think this is still relevant?

**Comment by eosram** [comment]
As previously mentioned this is up and running for some time. If there is still the need for refactoring, especially w.r.t the mentioned filter for nan values, this issue could be reopened or another issue will be filed, i guess.
