### ISSUE TITLE
Tidy up branches

### ISSUE THREAD

**Issue by ulfmueller** [openego/ego.powerflow#28]
@simnh Since the clustering has been moved to eTraGo would it be possible to delete the clustering branch: https://github.com/openego/ego.powerflow/tree/features/clustering ?

**Comment by simnh** [comment]
yes just delete....feel free

**Comment by ulfmueller** [comment]
ok.
@simnh the branch https://github.com/openego/ego.powerflow/tree/fix/table-name is also obsolete right?

**Comment by simnh** [comment]
jepp

**Comment by ulfmueller** [comment]
we would like to merge the branch [adaptions-of-tablenames](https://github.com/openego/ego.powerflow/tree/refactor/adaptions-of-tablenames) into the dev branch.
Before that we would do a release corresponding to the dev branch which will be the last release ego.powerflow working with the old database structure.
Any objections? @gplssm @nesnoj

**Comment by lukasol** [comment]
Go ahead.

**Comment by gplssm** [comment]
No objections here in Berlin.

**Comment by gplssm** [comment]
Remove [refactor/adaptions-of-tablenames](https://github.com/openego/ego.powerflow/tree/refactor/adaptions-of-tablenames) when #30 is resolved and close this issue.

**Comment by gplssm** [comment]
I removed refactor/upgrade-to-pypsa-0.8 and refactor/adaptions-of-tablenames
