### ISSUE TITLE
Merge 'refactor/upgrade-to-pypsa-0.8' into dev

### ISSUE THREAD

**Issue by gplssm** [openego/ego.powerflow#30]
Understand why Dingo produces different results with PyPSA 0.6.2 and 0.8.0

First you should make sure Dingo produces reproducible results: run multiple times with same setting and compare results. 

Possible reasons
1. API changes, i.e. p_min_pu/p_max_pu changed as @ulfmueller explained. See in [what's new of 0.7.0](https://pypsa.org/doc/release_notes.html#pypsa-0-7-0-20th-november-2016), [what's new of 0.7.1](https://pypsa.org/doc/release_notes.html#pypsa-0-7-1-26th-november-2016) and [what's new of 0.8.0](https://pypsa.org/doc/release_notes.html#pypsa-0-8-0-25th-january-2017)
2. Algorithms for PF in PyPSA changed

A basic analysis script to compare to Dingo results [is available here](https://gist.github.com/gplssm/34c5d48edd41676314bd26042ec9db27)

Note, there exists a new branch branched from  'refactor/upgrade-to-pypsa-0.8'  which contains latest development of ZNES/NExt Energy.

**Comment by gplssm** [comment]
The analysis of Dingo shows multiple runs return a different grid topology. On the example of MV grid 3545 it shows that the grid has sometime 280 nodes and on other runs 281 nodes. But, this is independent from PyPSA and different versions of PyPSA (see [point 5 of the dingo issue](https://github.com/openego/dingo/issues/200)).

Nevertheless, comparing nodes attributes (in particular results obtained from the power flow analysis) of runs with PyPSA 0.6.2 and PyPSA 0.8.0 shows good conformity. The voltage level resulting from the power flow analysis only deviates in the 10th decimal place.
Comparing edges data from both runs are perfect match of data is observed. 

To conclude, switching from PyPSA 0.6.2 to 0.8.0 does not affect Dingo results. :tada: :postal_horn:

**Comment by gplssm** [comment]
Merge is done!

**Comment by ulfmueller** [comment]
Would be nice to see if also 'our state of the art' branch [network-from-grid](https://github.com/openego/ego.powerflow/tree/refactor/network-from-grid) can be merged into dev too... maybe we can talk about that soon. In eTraGo we have been working with that branch in order to also access the grid schema and have some structural improvements. I can create an issue for that eventually...
