### ISSUE TITLE
Check oedb session compatibility to ego.io connection

### ISSUE THREAD

**Issue by ulfmueller** [openego/ego.powerflow#31]
Check out how the [session maker in ego.powerflow](https://github.com/openego/ego.powerflow/blob/dev/egopowerflow/tools/tools.py) works with the adjusted [session maker in ego.io](https://github.com/openego/ego.io/pull/24/commits/4c2caea68c7da5e633d1190b7b456d3eb8013e34). 

- [ ] Check if we can get rid of the function here in ego.powerflow and do that only in ego.io centrally.
- [ ] may be create a functionality that it is also possible to insert the session parameters manually
- [ ] ensure that the eTraGo (and others?) session connection works fine
- [ ] Approve the ego.io pull request (see above)

**Comment by mariusves** [comment]
This will be further handled in eTrago [here](https://github.com/openego/eTraGo/issues/61)!
