### ISSUE TITLE
high memory usage when using create_powerflow_problem()

### ISSUE THREAD

**Issue by mariusves** [openego/ego.powerflow#9]
When creating powerflow problem by using create_powerflow_problem() function, memory blows up to 10 GB (when importing HV grid). When using old ego.powerflow script memory is at ~250 MB.

**Comment by mariusves** [comment]
Issue still present:
when importing through e.g.
`network.import_components_from_dataframe(components['Line'],'Line')`
instead of 
`network.import_components_from_dataframe(components[Line],'Line')` (like in ego.powerflow.py)
memory usage increases significantly.

Might be a PyPSA `import_components_from_dataframe()` issue...

**Comment by gplssm** [comment]
For now, I don't it get why `network.import_components_from_dataframe(components[component],  str(component))` (from [mv_grid.py](https://github.com/openego/ego.powerflow/blob/deac6c35912272d7ecfcef026eec1a4f0988dd25/examples/mv_grid.py)) should be more memory consuming than `network.import_components_from_dataframe(component_data[Line],'Line')` (from [ego.powerflow.py](https://github.com/openego/ego.powerflow/blob/deac6c35912272d7ecfcef026eec1a4f0988dd25/egopowerflow/ego.powerflow.py)). `components` and `components_data` in both cases is a dict. In the first case dict keys are strings (i.e. 'Bus', 'Line', ...). In the latter example of [ego.powerflow.py](https://github.com/openego/ego.powerflow/blob/deac6c35912272d7ecfcef026eec1a4f0988dd25/egopowerflow/ego.powerflow.py) keys are SQLAlchemy orm objects (compare [the import in the variables `Bus`, `Line`, ...](https://github.com/openego/ego.powerflow/blob/deac6c35912272d7ecfcef026eec1a4f0988dd25/egopowerflow/ego.powerflow.py#L10) with the [keys that are used to access data from the dict](https://github.com/openego/ego.powerflow/blob/deac6c35912272d7ecfcef026eec1a4f0988dd25/egopowerflow/ego.powerflow.py#L199-#L204)). But this is just a side note.

I would like to compare the `components` dict of [ego.powerflow.py](https://github.com/openego/ego.powerflow/blob/deac6c35912272d7ecfcef026eec1a4f0988dd25/egopowerflow/ego.powerflow.py) to that one from an hv example file similar to to  [mv_grid.py](https://github.com/openego/ego.powerflow/blob/deac6c35912272d7ecfcef026eec1a4f0988dd25/examples/mv_grid.py) that uses `pypsa_io.py`. Could you please provide a script in the examples folder?

**Comment by mariusves** [comment]
You are right, for me it makes no sense why there is any difference between those two. I uploaded a short script, that allows to switch between both versions of import. Also I removed the`str()` on the `component` part from my previous commit since it didn't solve the problem.

**Comment by mariusves** [comment]
Memory issue appears when importing large networks with many components and setting the time range to a full year (8760 hours). Therefore not a bug, importer works as intended.
